---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2023/6/14 14:33
---

local FsmState_Push = {};

FsmState_Push.Name = "FsmState_Push";

function FsmState_Push:OnEnter(fsm)
    Logger.LogError("FsmState_Push:OnEnter...")

    --fsm:SwitchState("FsmState_Close");
end

function FsmState_Push:OnLeave(fsm)
    Logger.LogError("FsmState_Push:OnLeave...")
end

function FsmState_Push:OnCreate(fsm)

end

function FsmState_Push:OnDestroy(fsm)

end

function FsmState_Push:OnTick(fsm)
    Logger.LogError("FsmState_Push:OnTick...")
end 

return FsmState_Push