---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2023/6/14 14:34
---

local FsmState_Close = {};

FsmState_Close.Name = "FsmState_Close";

function FsmState_Close:OnEnter(fsm)
    Logger.LogError("FsmState_Close:OnEnter...")
end

function FsmState_Close:OnLeave(fsm)
    Logger.LogError("FsmState_Close:OnLeave...")
end

function FsmState_Close:OnCreate(fsm)

end

function FsmState_Close:OnDestroy(fsm)

end

function FsmState_Close:OnTick(fsm)
    Logger.LogError("FsmState_Close:OnTick...")
end

return FsmState_Close;