---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2023/6/14 14:33
---

local FsmState_Open = {};

FsmState_Open.Name = "FsmState_Open";

function FsmState_Open:OnEnter(fsm)
    Logger.LogError("FsmState_Open:OnEnter...")

    --fsm:SwitchState("FsmState_Push");
end

function FsmState_Open:OnLeave(fsm)
    Logger.LogError("FsmState_Open:OnLeave...")
end

function FsmState_Open:OnCreate(fsm)

end

function FsmState_Open:OnDestroy(fsm)

end

function FsmState_Open:OnTick(fsm)

end 

return FsmState_Open;